server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    charset: UTF-8
    cache: false
    settings:
      number_format: computer
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      output_encoding: UTF-8

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
